In [1]:
import os
print(os.getcwd())
os.chdir('D:/handwritten')
print(os.getcwd())

C:\Users\Administrator
D:\handwritten


In [9]:
import numpy as np
features_pca = np.load('top100_features_Proportional_80_pca.npy')
labels = np.load('top100_Labels_Proportional.npy')
print("labels：", labels.shape)
print("features_pca：", features_pca.shape)

labels： (60261,)
features_pca： (60261, 26)


In [10]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# create LabelEncoder instance
label_encoder = LabelEncoder()

# Convert the string category label to an integer
y_encoded = label_encoder.fit_transform(labels)

# Assign the PCA-processed features to X
X = features_pca

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [11]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# SVM
svm = SVC(kernel='linear')  # Choose rbf kernel maybe better
svm.fit(X_train, y_train)

svm_predictions = svm.predict(X_test)

print("SVM Classification Report:")
print(classification_report(y_test, svm_predictions))
print("SVM Accuracy:", accuracy_score(y_test, svm_predictions))

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.58      0.56        45
           1       0.54      0.34      0.42       312
           2       0.00      0.00      0.00       165
           3       0.64      0.24      0.35        29
           4       0.59      0.46      0.52        35
           5       0.20      0.02      0.04        42
           6       0.64      0.88      0.74      1113
           7       0.70      0.85      0.76        65
           8       0.84      0.86      0.85       964
           9       0.77      0.66      0.71        35
          10       0.74      0.57      0.65        40
          11       0.88      0.42      0.57        55
          12       1.00      0.04      0.07        56
          13       0.00      0.00      0.00        38
          14       0.00      0.00      0.00        26
          15       0.00      0.00      0.00        45
          16       0.00      0.00      0.00        71


C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r

In [12]:
from joblib import dump, load
dump(svm, '80_svm_model.joblib')

['80_svm_model.joblib']

In [13]:
import pickle

# 保存模型
with open('80_svm_model.pickle', 'wb') as f:
    pickle.dump(svm, f)

In [8]:
# 从文件加载模型
svm_loaded = load('svm_model.joblib')

# 使用加载的模型进行预测
predictions = svm_loaded.predict(X_test)
print("Loaded model accuracy:", accuracy_score(y_test, predictions))

Loaded model accuracy: 0.4415498216211732


In [10]:
from sklearn.metrics import confusion_matrix, matthews_corrcoef
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report

# 预测75
svm_predictions = svm.predict(X_test)

# 计算基础评估指标
print("Accuracy:", accuracy_score(y_test, svm_predictions))
print("Precision (Macro-average):", precision_score(y_test, svm_predictions, average='macro'))
print("Recall (Macro-average):", recall_score(y_test, svm_predictions, average='macro'))
print("F1 Score (Macro-average):", f1_score(y_test, svm_predictions, average='macro'))
print("F1 Score (Micro-average):", f1_score(y_test, svm_predictions, average='micro'))
print("F1 Score (Weighted-average):", f1_score(y_test, svm_predictions, average='weighted'))

# 混淆矩阵
cm = confusion_matrix(y_test, svm_predictions)
print("Confusion Matrix:\n", cm)

# Matthews 相关系数
mcc = matthews_corrcoef(y_test, svm_predictions)
print("Matthews Correlation Coefficient:", mcc)

# 详细分类报告
print("Detailed classification report:\n")
print(classification_report(y_test, svm_predictions))


Accuracy: 0.4415498216211732
Precision (Macro-average): 0.22303808565555389
Recall (Macro-average): 0.17236039904407308
F1 Score (Macro-average): 0.1690514464842048
F1 Score (Micro-average): 0.4415498216211732
F1 Score (Weighted-average): 0.3678832702346053
Confusion Matrix:
 [[14  0  1 ...  0  0  0]
 [ 0 79  1 ...  0  0  0]
 [ 0  7  2 ...  0  0  0]
 ...
 [ 0  0  0 ... 87  0  0]
 [ 0  0  0 ...  1  1  0]
 [ 0  0  0 ...  0  0 40]]
Matthews Correlation Coefficient: 0.41282627666875055
Detailed classification report:

              precision    recall  f1-score   support

           0       0.54      0.31      0.39        45
           1       0.49      0.25      0.33       312
           2       0.17      0.01      0.02       165
           3       0.67      0.07      0.12        29
           4       0.40      0.23      0.29        35
           5       0.00      0.00      0.00        42
           6       0.62      0.88      0.73      1113
           7       0.56      0.80      0.66    

C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\ProgramData\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r

In [8]:
from sklearn.metrics import confusion_matrix, matthews_corrcoef
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report

# 预测90
svm_predictions = svm.predict(X_test)

# 将预测结果和实际标签转换回原始字符串标签
svm_predictions_labels = label_encoder.inverse_transform(svm_predictions)
y_test_labels = label_encoder.inverse_transform(y_test)

# 计算基础评估指标
print("Accuracy:", accuracy_score(y_test, svm_predictions))
print("Precision (Macro-average):", precision_score(y_test, svm_predictions, average='macro'))
print("Recall (Macro-average):", recall_score(y_test, svm_predictions, average='macro'))
print("F1 Score (Macro-average):", f1_score(y_test, svm_predictions, average='macro'))
print("F1 Score (Micro-average):", f1_score(y_test, svm_predictions, average='micro'))
print("F1 Score (Weighted-average):", f1_score(y_test, svm_predictions, average='weighted'))

# 混淆矩阵
cm = confusion_matrix(y_test_labels, svm_predictions_labels)
print("Confusion Matrix:\n", cm)

# Matthews 相关系数
mcc = matthews_corrcoef(y_test, svm_predictions)
print("Matthews Correlation Coefficient:", mcc)

# 详细分类报告
print("Detailed classification report:\n")
print(classification_report(y_test_labels, svm_predictions_labels))


Accuracy: 0.6287231394673525
Precision (Macro-average): 0.4992921979138359
Recall (Macro-average): 0.4396726353712934
F1 Score (Macro-average): 0.45757556933734267
F1 Score (Micro-average): 0.6287231394673525
F1 Score (Weighted-average): 0.6100694896627278
Confusion Matrix:
 [[ 31   0   0 ...   0   0   0]
 [  1 163   3 ...   0   0   0]
 [  0  10   3 ...   0   0   0]
 ...
 [  0   0   0 ...  88   1   0]
 [  0   0   0 ...   0  22   0]
 [  0   2   0 ...   0   0  41]]
Matthews Correlation Coefficient: 0.6121363909132537
Detailed classification report:

              precision    recall  f1-score   support

           !       0.65      0.69      0.67        45
           "       0.58      0.52      0.55       312
           '       0.17      0.02      0.03       165
          's       0.53      0.34      0.42        29
           (       0.44      0.46      0.45        35
           )       0.53      0.19      0.28        42
           ,       0.68      0.89      0.77      1113
           - 

In [11]:
# 如果需要，将预测的整数标签转回原始字符串
y_pred_labels = label_encoder.inverse_transform(predictions.astype(int))

In [12]:
print(y_pred_labels)

['to' ',' 'the' ... 'and' ',' 'in']
